// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'chrome://resources/cr_elements/cr_icon_button/cr_icon_button.m.js';
import 'chrome://resources/cr_elements/cr_icons_css.m.js';

import {html, Polymer} from 'chrome://resources/polymer/v3_0/polymer/polymer_bundled.min.js';

import {AutogeneratedThemeColorInfo} from '../manage_profiles_browser_proxy.js';
import {navigateToPreviousRoute} from '../navigation_behavior.js';

Polymer({
  is: 'profile-type-choice',

  _template: html`{__html_template__}`,

  properties: {
    /** @type {!AutogeneratedThemeColorInfo} */
    profileThemeInfo: {
      type: Object,
    },
  },

  /** @private */
  onTapBack_() {
    navigateToPreviousRoute();
  },
});
