// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import {addSingletonGetter, sendWithPromise} from 'chrome://resources/js/cr.m.js';

/**
 * This is the data structure sent back and forth between C++ and JS.
 * @typedef {{
 *   profilePath: string,
 *   localProfileName: string,
 *   gaiaName: string,
 *   avatarIcon: string,
 * }}
 */
export let ProfileState;

/**
 * This is the data structure sent back and forth between C++ and JS.
 * @typedef {{
 *   colorId: number,
 *   themeColor: string,
 * }}
 */
export let AutogeneratedThemeColorInfo;

/** @interface */
export class ManageProfilesBrowserProxy {
  /**
   * Initializes profile picker main view.
   */
  initializeMainView() {}

  /**
   * Launches picked profile and closes the profile picker.
   * @param {string} profilePath
   */
  launchSelectedProfile(profilePath) {}

  /**
   * Inform native the user's choice on whether to show the profile picker
   * on startup or not.
   * @param {boolean} shouldShow
   */
  askOnStartupChanged(shouldShow) {}

  /**
   * Retrieves suggested theme for the new profile.
   * @return {!Promise<!AutogeneratedThemeColorInfo>} A promise firing with the
   * suggested theme info, once it has been retrieved.
   */
  getNewProfileSuggestedThemeInfo() {}
}

/** @implements {ManageProfilesBrowserProxy} */
export class ManageProfilesBrowserProxyImpl {
  /** @override */
  initializeMainView() {
    chrome.send('mainViewInitialize');
  }

  /** @override */
  launchSelectedProfile(profilePath) {
    chrome.send('launchSelectedProfile', [profilePath]);
  }

  /** @override */
  askOnStartupChanged(shouldShow) {
    chrome.send('askOnStartupChanged', [shouldShow]);
  }

  /** @override */
  getNewProfileSuggestedThemeInfo() {
    return sendWithPromise('getNewProfileSuggestedThemeInfo');
  }
}

addSingletonGetter(ManageProfilesBrowserProxyImpl);
